version: '3.8'

services:
  project-management:
    image: project-management
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
        - PORT=${PORT}
    environment:
      - DEBUG=${DEBUG}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    command: node dist/main.js
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_PORT=80
    depends_on:
      - project-management

volumes:
  mongo-data:
