version: '3.8'

services:
  project-management:
    image: project-management
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
        - PORT=${PORT}
    environment:
      - DEBUG=${DEBUG}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - PASSWORD_SALT=${PASSWORD_SALT}
      - JWT_AUTH_TOKEN_EXPIRE_IN=${JWT_AUTH_TOKEN_EXPIRE_IN}
      - JWT_REFRESH_TOKEN_EXPIRE_IN=${JWT_REFRESH_TOKEN_EXPIRE_IN}
    volumes:
      - ./:/app:ro
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
      - PORT=8081
    depends_on:
      - mongo

  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_PORT=80
    depends_on:
      - project-management
      - mongo-express


